Repository kubesphere-sigs/katacoda-scenarios, pull requests merged in 2021-11, with the labels that each got.

#5 Fix the 404 of devops scenario
  profile-pathway.json
Labels: size/XS

#7 Add AbdelouahabMbarki, LinuxSuRen as approvers
  OWNERS
Labels: size/XS, chore

#8 Fix the broken link of KubeSphere LOGO
  Install-kubesphere-on-kubernetes/intro.md
  KubeSphere DevOps/assets/images/kubesphere-logo.png
  KubeSphere DevOps/intro.md
  assets/kubesphere-logo.png
Labels: bug, size/XS, lgtm

#4 Add an instruct about how to add a new scenario
  README.md
Labels: size/XS
